### ISSUE TITLE
'master' to 'main'

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edam-popovers#4]
Would you mind if we rename the `master` branch to `main`, following the global🌏 & universal🌌 liberation and inclusion trend?
✊🏽🤝🏽🏳‍🌈👩🏽‍💻✌🏽

It will mean a tiny bit of setup in local clones, but GitHub helps very nicely with the move👍🏽

**Comment by inkuzmin** [comment]
It should be renamed now, here are the commands to update local clones:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by matuskalas** [comment]
Million giant thanks @inkuzmin!!!
